name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y unzip curl git openjdk-11-jdk

    - name: Build APK
      run: ./build.sh # или твоя сборочная команда

    - name: Archive (альтернатива upload-artifact)
      run: zip -r xmrig.apk.zip ./путь_к_apk
